# Copyright 2021 root
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  port-1:
    description: Radius port 1
    type: int
    default: 1812
  port-2:
    description: Radius port 2
    type: int
    default: 1813
  image:
    description: Docker image name
    type: string
    default: daviddvss/freeradiuspy

